#ifndef __MVT_TIMER_H__
#define __MVT_TIMER_H__

typedef enum ENUM_TIMER
{
	TIMER_FRAME=0,
	TIMER_SAMPLING,
	TIMER_SAMPLING_VIEWPOINT,
	TIMER_SAMPLING_CENTER,
	TIMER_SAMPLING_CENTER_COPY1,
	TIMER_SAMPLING_CENTER_COPY2,
	TIMER_SAMPLING_CENTER_COPY3,
	TIMER_SAMPLING_CENTER_COPY4,
	TIMER_SAMPLING_CENTER_RNDGEN,
	TIMER_SAMPLING_CENTER_RECTIFY,
	TIMER_CLASSIFIER_UPDATE,
	TIMER_COMPUTE_POTENTIAL,
	TIMER_COMPUTE_POTENTIAL_NORMALIZE,
	TIMER_ALM,
	TIMER_ALM_CROP,
	TIMER_ALM_DOT,
	TIMER_ALM_DOT_ALLOC,
	TIMER_ALM_DOT_CAL,
	TIMER_ALM_DOT_FREE,
	TIMER_ALM_FREE,
	TIMER_ALM_OTHER,
	TIMER_MIL,
	TIMER_MIL_OCC,
	TIMER_MIL_MAKE_SAMPLE,
	TIMER_MIL_CAL,
	TIMER_MIL_WEIGHT,
	TIMER_MIL_CUDA_ALLOC,
	TIMER_MIL_CUDA_MEMCPY,
	TIMER_MIL_CUDA_CAL,
	TIMER_MIL_CUDA_FREE,
	NUM_OF_TIMER
}ENUM_TIMER;

unsigned long tic(ENUM_TIMER timer);
unsigned long toc(ENUM_TIMER timer);
void tic_count(ENUM_TIMER timer);
void toc_count(ENUM_TIMER timer);
unsigned long count(ENUM_TIMER timer);
void count_init(ENUM_TIMER timer);

#define TIMER 0


#endif
